on: 
  push:
    branches:
      - master
name: ðŸš€ Deploy website on push master
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: ðŸ“‚ Sync files Laravel
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.wakimart.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /laravel_wakiindonesia_betatester/
        exclude: public/**
          - public/
          - .git*
          - .git*/**
          -  **/.git*/**
          - node_modules/**
          - node_modules/**/*
        
    - name: ðŸ“‚ Sync files public
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.wakimart.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./public/
        server-dir: /public_html/betawakiindo/
        exclude: .htaccess
          - credentials.json
          - favicon.ico
          - index.php
          - robots.txt
          - web.config
